name: 🏷️ Label Management

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/label-management.yml'

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              {
                name: 'join-request',
                color: '0052cc',
                description: 'Request to join the organization'
              },
              {
                name: 'invite-sent',
                color: '28a745',
                description: 'Organization invitation has been sent'
              },
              {
                name: 'invite-failed',
                color: 'd73a49',
                description: 'Failed to send organization invitation'
              },
              {
                name: 'pending-review',
                color: 'fbca04',
                description: 'Join request requires manual review'
              },
              {
                name: 'approved',
                color: '28a745',
                description: 'Join request has been approved'
              },
              {
                name: 'member-joined',
                color: '7057ff',
                description: 'User has successfully joined the organization'
              }
            ];

            for (const label of labels) {
              try {
                // Try to get the existing label
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name
                });
                
                // If it exists, update it
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
                
                console.log(`Updated label: ${label.name}`);
              } catch (error) {
                if (error.status === 404) {
                  // Label doesn't exist, create it
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });
                  
                  console.log(`Created label: ${label.name}`);
                } else {
                  console.error(`Error managing label ${label.name}:`, error);
                }
              }
            }
